allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@myrmidon/cadmus-part-general-pg@18.0.0'
  - '@myrmidon/cadmus-part-general-ui@18.0.1'
  - '@myrmidon/cadmus-text-ed-md@12.0.0'
  - '@myrmidon/cadmus-text-ed-txt@11.0.0'
  - '@myrmidon/cadmus-text-ed@11.0.0'
  - '@myrmidon/cadmus-ui-note-set@12.0.0'
  - '@rollup/rollup-win32-arm64-msvc@4.62.0 || 4.64.0'
hoistPattern:
  - '*'
  - '!zone.js'
