allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@myrmidon/cadmus-part-general-pg@18.0.0 || 20.0.0'
  - '@myrmidon/cadmus-part-general-ui@18.0.1 || 20.0.0'
  - '@myrmidon/cadmus-text-ed-md@12.0.0'
  - '@myrmidon/cadmus-text-ed-txt@11.0.0'
  - '@myrmidon/cadmus-text-ed@11.0.0'
  - '@myrmidon/cadmus-ui-note-set@12.0.0'
  - '@rollup/rollup-win32-arm64-msvc@4.62.0 || 4.64.0'
  - '@myrmidon/cadmus-api@20.0.0'
  - '@myrmidon/cadmus-core@20.0.0'
  - '@myrmidon/cadmus-flags-pg@20.0.0'
  - '@myrmidon/cadmus-flags-ui@20.0.0'
  - '@myrmidon/cadmus-graph-pg@20.0.0'
  - '@myrmidon/cadmus-graph-ui@20.0.0'
  - '@myrmidon/cadmus-item-editor@20.0.0'
  - '@myrmidon/cadmus-item-list@20.0.0'
  - '@myrmidon/cadmus-item-search@20.0.0'
  - '@myrmidon/cadmus-preview-pg@20.0.0'
  - '@myrmidon/cadmus-preview-ui@20.0.0'
  - '@myrmidon/cadmus-profile-core@20.0.0'
  - '@myrmidon/cadmus-state@20.0.0'
  - '@myrmidon/cadmus-statistics@20.0.0'
  - '@myrmidon/cadmus-thesaurus-editor@20.0.0'
  - '@myrmidon/cadmus-thesaurus-list@20.0.0'
  - '@myrmidon/cadmus-thesaurus-ui@20.0.0'
  - '@myrmidon/cadmus-ui@20.0.0'
hoistPattern:
  - '*'
  - '!zone.js'
